version: "3.7"
services:

  db:
    image: mysql
    container_name: db_docker_sedenthere
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: sedenthere
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_sedenthere
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_sedenthere
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8082:80"
    restart: always
    networks:
      - dev

  www:
    build: ./docker/php
    container_name: www_docker_sedenthere
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    labels:
      - "traefik.http.routers.sedenthere.rule=Host(`sedenthere.traefik.me`)"
      - "traefik.http.routers.sedenthere-tls.tls.domains[0].main=sedenthere.traefik.me"
      - "traefik.http.routers.sedenthere-tls.tls.domains[0].sans=sedenthere-*.traefik.me"
      - "traefik.http.routers.sedenthere.tls=true"
    networks:
      - dev

  traefik:
    restart: unless-stopped
    container_name: traefik_docker_sedenthere
    image: traefik:v2.0.2
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - ./docker/traefik.yml:/etc/traefik/traefik.yml
      - ./docker/tls.yml:/etc/traefik/tls.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/etc/ssl/traefik
    networks:
      - dev

  reverse-proxy-https-helper:
    image: alpine
    container_name: alpine_docker_sedenthere
    command: sh -c "cd /etc/ssl/traefik
      && wget traefik.me/cert.pem -O cert.pem
      && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - certs:/etc/ssl/traefik
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
  certs: